version: '3'
services:
  llm:
    image: ollama/ollama:latest
    ports: "11434:11434"
    networks:
      - posnet
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - posnet
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    networks:
      - posnet
  web:
    container_name: pos-app
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - llm

networks:
  posnet:
    driver: bridge