version: '3'
services:
  llm:
    image: ollama/ollama:latest
    ports: 
      - "11434:11434"
    networks:
      - posnet
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - posnet
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    networks:
      - posnet
  qdrant:
      image: qdrant/qdrant:latest
      restart: always
      container_name: qdrant
      ports:
        - 6333:6333
        - 6334:6334
      expose:
        - 6333
        - 6334
        - 6335
      volumes:
        - ./qdrant_data:/qdrant_data
      networks:
        - posnet

  web:
    container_name: pos-app
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - llm

networks:
  posnet:
    driver: bridge
