version: '3'
services:
  llm:
    image: ollama/ollama:latest
    ports: 
      - "11434:11434"
    networks:
      - posnet
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - posnet
  pg_db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev
    ports:
      - "5432:5432"
    networks:
      - posnet
  web:
    container_name: pos-app
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - pg_db
      - redis
      - llm

networks:
  posnet:
    driver: bridge
